name: "rust-install"
description: "Install a Rust binary as fast as possible"
author: "ironcorelabs"
branding:
  icon: play-circle
  color: black
inputs:
  crate:
    description: Binary crate name
    required: true
  accesskey:
    description: AWS access key
    required: true
  secretkey:
    description: AWS secret key
    required: true
  version:
    description: Specify a version to install
    required: false
    default: "latest"
runs:
  using: "node12"
  main: "dist/index.js"
