name: "rust-install"
description: "Install a Rust binary as fast as possible"
author: "ironcorelabs"
branding:
  icon: play-circle
  color: gray-dark
inputs:
  crate:
    description: Binary crate name
    required: true
  accesskey:
    description: AWS access key
    required: true
  secretkey:
    description: AWS secret key. If not provided or blank, skips the tool cache.
    required: false
  os:
    description: OS for the runner (ex. ubuntu-20.04)
    required: false
  version:
    description: Specify a version to install
    required: false
    default: "latest"
runs:
  using: "node20"
  main: "dist/index.js"
